### PR TITLE
core/locale: fix data race and improve devmode performance in translation service

### LINKED ISSUE #188: core/locale: Data race in translation_service
We just witnessed a race condition in the translation service. We should add some sort of mutex to avoid that. 

```
==================
==================
WARNING: DATA RACE
Read at 0x00c0005215c9 by goroutine 132:
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).loadFiles()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:127 +0x64
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).initAndLoad()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:154 +0x84
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).Translate()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:70 +0x4f
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).JSONError()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:222 +0x401
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).SearchFlightsAction()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:98 +0x6c7
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).SearchFlightsAction-fm()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:81 +0x74
  flamingo.me/flamingo/v3/framework/web.(*handler).ServeHTTP.func3()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/handler.go:163 +0x481
  flamingo.me/flamingo/v3/framework/web.(*FilterChain).Next()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter.go:58 +0x24d
  flamingo.me/flamingo/v3/framework/web/filter.(*MetricsFilter).Filter()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter/request_metrics_filter.go:84 +0x7a
  flamingo.me/flamingo/v3/framework/web.(*FilterChain).Next()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter.go:63 +0x1a2
  flamingo.me/flamingo/v3/framework/web.(*handler).ServeHTTP()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/handler.go:174 +0xc12
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d
Previous write at 0x00c0005215c9 by goroutine 36:
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).loadFiles()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:147 +0x199
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).initAndLoad()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:154 +0x84
  flamingo.me/flamingo/v3/core/locale/infrastructure.(*TranslationService).Translate()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/core/locale/infrastructure/translation_service.go:70 +0x4f
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).JSONError()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:222 +0x401
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).DeleteSessionFlightAction()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:134 +0x27c
  go.aoe.com/flamingo-om3/v3/om3flight/interfaces/controller.(*FlightAPIController).DeleteSessionFlightAction-fm()
      /builds/shared/flamingo/flamingo-om3/om3flight/interfaces/controller/flightapicontroller.go:131 +0x74
  flamingo.me/flamingo/v3/framework/web.(*handler).ServeHTTP.func3()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/handler.go:163 +0x481
  flamingo.me/flamingo/v3/framework/web.(*FilterChain).Next()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter.go:58 +0x24d
  flamingo.me/flamingo/v3/framework/web/filter.(*MetricsFilter).Filter()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter/request_metrics_filter.go:84 +0x7a
  flamingo.me/flamingo/v3/framework/web.(*FilterChain).Next()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/filter.go:63 +0x1a2
  flamingo.me/flamingo/v3/framework/web.(*handler).ServeHTTP()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo/v3@v3.2.2/framework/web/handler.go:174 +0xc12
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2887 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1952 +0x87d
Goroutine 132 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3013 +0x644
  flamingo.me/flamingo-commerce/v3/test/integrationtest.(*testModule).startServer.func1()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo-commerce/v3@v3.4.1-0.20210216092306-6b72b16596d5/test/integrationtest/helper.go:98 +0x6a
Goroutine 36 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:3013 +0x644
  flamingo.me/flamingo-commerce/v3/test/integrationtest.(*testModule).startServer.func1()
      /builds/shared/flamingo/flamingo-om3/.go/pkg/mod/flamingo.me/flamingo-commerce/v3@v3.4.1-0.20210216092306-6b72b16596d5/test/integrationtest/helper.go:98 +0x6a
==================
```

### LINKED ISSUE #193: core/locale: bad performance for translations endpoint in debug mode
We noticed that the [translations endpoint](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/module.go#L47-L48) in the core/locale module is really slow in flamingo debug mode. This is because in debug mode, we reload the translation files for each translation (see [TranslateLabel](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/infrastructure/translation_service.go#L48) and [loadFiles](https://github.com/i-love-flamingo/flamingo/blob/master/core/locale/infrastructure/translation_service.go#L127) methods). In the translations endpoint we list every translation, so we reload the translation files hundreds of times.  It would make sense to only reload when necessary (e. g. a translation file changed).

### PR DESCRIPTION
**Pull request by SchiffFlieger**
Fixes #188 and fixes #193. With the change we only reload the translations if one of the translationfiles changed. Only applies for debug mode, in production mode we still just load them once.

### CODE REVIEW

File: core/locale/infrastructure/translation_service.go [hunk 1]
```diff
@@ -123,33 +134,43 @@ func (ts *TranslationService) translateWithLib(localeCode string, key string, co
...
 	}
-	ts.filesLoaded = true
+
+	ts.RLock()
+	lastReload := ts.lastReload
+	ts.RUnlock()
+
+	if lastFileChange.After(lastReload) {
+		ts.loadFiles()
+	}
```
Comment (SchiffFlieger) [inline core/locale/infrastructure/translation_service.go:161]: This part is still not perfect. Actually we should reload the files without giving away the lock. But as far as I know, Go has no way to upgrade the read lock to a write lock. If you have any ideas how to improve this, please let me know. 
It's not too bad though. Worst case is that we reload the translations again without file changes. As it only happens in debug mode, I think it's okay for now.

File: core/locale/infrastructure/translation_service.go [hunk 2]
```diff
@@ -4,22 +4,24 @@ import (
...
 	"flamingo.me/flamingo/v3/framework/config"
 	"flamingo.me/flamingo/v3/framework/flamingo"
 	"github.com/nicksnyder/go-i18n/i18n/bundle"
 )
 
 // TranslationService is the default TranslationService implementation
 type TranslationService struct {
-	translationFile  string
-	translationFiles config.Slice
+	sync.RWMutex
```
Comment (tessig) [inline core/locale/infrastructure/translation_service.go:20]: I would use a named private field here, otherwise we expose all the Lock/Unlock methods and I don't think we want outside users to lock the TranslationService.

File: core/locale/infrastructure/translation_service.go (hunk 1 above)
Comment (tessig) [reply core/locale/infrastructure/translation_service.go:161]: You could prevent this by using github.com/golang/groupcache/singleflight as we do it in core/cache: While loading a cache entry from the backend, all other incoming load requests wait for the result instead of load it again.

But I'm not sure if this case is worth the effort.

File: core/locale/infrastructure/translation_service.go (hunk 2 above)
Comment (SchiffFlieger) [reply core/locale/infrastructure/translation_service.go]: You're right, I changed it.

File: core/locale/infrastructure/translation_service.go (hunk 1 above)
Comment (SchiffFlieger) [reply core/locale/infrastructure/translation_service.go]: I played around with the singleflight for a while, but couldn't get the synchronization right. In the end, I decided to move away from the R/W lock and just use a normal mutex. Even without parallel reads it's still much faster than before.

Comment (tessig) [reply core/locale/infrastructure/translation_service.go]: nice, I totally agree

**Review by tessig — APPROVED** [review]
